openapi: 3.1.0
info:
  title: Rolodex Test Data
  version: 1.0.0
paths:
  /one/local/schema:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Thing'
  /one/far/away/reference:
    $ref: '../paths/a-tag/an-endpoint/a-method.yaml'
components:
  schemas:
    Thing:
      type: object
      description: A thing that does nothing.
      properties:
        message:
          type: string
          description: I am pointless.